blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import hello_world
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello_world),
    path('', include('website.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import hello_blog
from .views import post_detail
from .views import save_form

urlpatterns = [
    path('', hello_blog, name='home_blog'),
    path('post/<int:id>/', post_detail, name='post_detail'),
    path('save-form/', save_form, name='save_form'),
] 

website/models.py
from django.db import models

class Categorias(models.TextChoices):
    TECH = 'TC', 'Tecnologia'
    CR = 'CR', 'Curiosidades'
    GR = 'GR', 'Geral'

class Post(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=200)
    content = models.TextField() #tamanho em aberto
    categories = models.CharField(max_length=2,
                        choices=Categorias.choices,
                        default=Categorias.GR)
    approved = models.BooleanField(default=True)
    image = models.ImageField(upload_to='posts', null=True, blank=True)

    def __str__(self):

        return self.title

    def full_name(self):
        return self.title + ' ' + self.sub_title

    full_name.admin_order_field = 'title'

class Contact(models.Model):

    name = models.CharField(max_length=150)
    email = models.EmailField()
    message = models.TextField()

blog/views.py
from django.http import HttpResponse

def hello_world(request):
    return HttpResponse('Hello World')

website/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from .models import Contact
def hello_blog(request):
    lista = ['Django', 'Python', 'Git', 'HTML', 'Banco de Dados', 'Linux', 'Nginx', 'Uwsgi']

    lista_post =  Post.objects.filter(approved=True)

    data = {'name': 'Curso de Django 3', 
    'lista_tecnologias': lista,
    'posts': lista_post    
    }

    return render(request, 'index.html', data)

def post_detail(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'post_detail.html', {'post': post})


def save_form(request):
    nome = request.POST['name']
    Contact.objects.create(
        name = nome,
        email = request.POST['email'],
        message = request.POST['message']
    )

    return render(request, 'contact_success.html', {'name_contact': nome})

website/templates/contact_success.html
<h1>Obrigado {{ name_contact }}, seu contato foi recebido com sucesso!</h1>

website/templates/index.html
{% load static %}

<!DOCTYPE HTML>
<!--
	Strata by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Strata by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport"  content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<div class="inner">
					<a href="#"  class="image avatar"><img src="{% static 'images/avatar.jpg' %}" alt="" /></a>
					<h1><strong>I am Strata</strong>, a super simple<br />
					responsive site template freebie<br />
					crafted by <a href="http://html5up.net">HTML5 UP</a>.</h1>
				</div>
			</header>

		<!-- Main -->
			<div id="main">

				<!-- One -->
					<section id="one">
						<header class="major">
							<h2>Ipsum lorem dolor aliquam ante commodo<br />
							magna sed accumsan arcu neque.</h2>
						</header>
						<p>Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia.</p>
						<ul class="actions">
							<li><a href="#"  class="button">Learn More</a></li>
						</ul>
					</section>

				<!-- Two -->
					<section id="two">
						<h2>Recent Work</h2>
						<div class="row">

                            {% for post in posts %}
								
								{% if post.image %}

									<a href="{{ post.image.url }}"  class="image fit thumb">
										<img src="{{ post.image.url }}" alt="" />
									</a>
								{% else %}
									<a href="{% static 'images/thumbs/01.jpg' %}"  class="image fit thumb">
										<img src="{% static 'images/thumbs/01.jpg' %}" alt="" />
									</a>
								{% endif %}
							

                                <article class="col-6 col-12-xsmall work-item">

                                    <h3>{{ post.title }}</h3>
                                    <p>{{ post.sub_title }}</p>
                                    <spam>{{ post.get_categories_display }}</spam>
									<ul class="actions">
										<li><a href="{% url 'post_detail' post.id %}"  class="button">Read More</a></li>
									</ul>
                                </article>

                            {% endfor %}
						</div>
						<ul class="actions">
							<li><a href="{% static '#'  %} "  class="button">Full Portfolio</a></li>
						</ul>
					</section>

				<!-- Three -->
					<section id="three">
						<h2>Get In Touch</h2>
						<p>Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor.</p>
						<div class="row">
							<div class="col-8 col-12-small">
								<form method="post" action="{% url 'save_form' %}">

									{% csrf_token %}

									<div class="row gtr-uniform gtr-50">
										<div class="col-6 col-12-xsmall"><input type="text" name="name" id="name" placeholder="Name" /></div>
										<div class="col-6 col-12-xsmall"><input type="email" name="email" id="email" placeholder="Email" /></div>
										<div class="col-12"><textarea name="message" id="message" placeholder="Message" rows="4"></textarea></div>
									</div>
								
									<ul class="actions">
										<li><input type="submit" value="Send Message" /></li>
									</ul>
								</form>
							</div>
							<div class="col-4 col-12-small">
								<ul class="labeled-icons">
									<li>
										<h3 class="icon solid fa-home"><span class="label">Address</span></h3>
										1234 Somewhere Rd.<br />
										Nashville, TN 00000<br />
										United States
									</li>
									<li>
										<h3 class="icon solid fa-mobile-alt"><span class="label">Phone</span></h3>
										000-000-0000
									</li>
									<li>
										<h3 class="icon solid fa-envelope"><span class="label">Email</span></h3>
										<a href="{% static '#">hello@untitled.tld</a>
									</li>
								</ul>
							</div>
						</div>
					</section>


			</div>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<ul class="icons">
						<li><a href="#"  class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#"  class="icon brands fa-github"><span class="label">Github</span></a></li>
						<li><a href="#"  class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
						<li><a href="#"  class="icon solid fa-envelope"><span class="label">Email</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled</li><li>Design: <a href="{% static 'http://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js'  %} "></script>
			<script src="{% static 'assets/js/jquery.poptrox.min.js'  %} "></script>
			<script src="{% static 'assets/js/browser.min.js'  %} "></script>
			<script src="{% static 'assets/js/breakpoints.min.js'  %} "></script>
			<script src="{% static 'assets/js/util.js'  %} "></script>
			<script src="{% static 'assets/js/main.js'  %} "></script>

	</body>
</html>

website/templates/index_didatico.html
<h1> BLOG </h1>

{{ name }}

<ul>
{% for item in lista_tecnologias %}

    {% if item == 'Django' %}
        
        <li><b> {{ item }} </b></li> 

    {% else %}

        <li> {{ item }} </li> 

    {% endif %}

{% endfor %}
</ul>

<ul>

    {% for post in posts %}

        <h2> {{ post.title }}</h2>

        <h3> {{ post.sub_title }}</h3>

        <h4> {{ post.content }}</h4>
        
    {% endfor %}

</ul>

website/templates/post_detail.html
{% load static %}

<!DOCTYPE HTML>
<!--
	Strata by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Strata by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport"  content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
	</head>
	<body class="is-preload">

		<!-- Main -->
			<div id="main">

				<!-- One -->
					<section id="one">
						<header class="major">
							<h2> {{ post.title}}</h2>
                            <H4> {{ post.sub_title }}</H4>
						</header>
						<p>{{post.content}}</p>
						<img src="{{ post.image.url }}">
						<ul class="actions">
							<li><a href="{% url 'home_blog' %}"  class="button">Return</a></li>
						</ul>
					</section>

			</div>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<ul class="icons">
						<li><a href="#"  class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#"  class="icon brands fa-github"><span class="label">Github</span></a></li>
						<li><a href="#"  class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
						<li><a href="#"  class="icon solid fa-envelope"><span class="label">Email</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled</li><li>Design: <a href="{% static 'http://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js'  %} "></script>
			<script src="{% static 'assets/js/jquery.poptrox.min.js'  %} "></script>
			<script src="{% static 'assets/js/browser.min.js'  %} "></script>
			<script src="{% static 'assets/js/breakpoints.min.js'  %} "></script>
			<script src="{% static 'assets/js/util.js'  %} "></script>
			<script src="{% static 'assets/js/main.js'  %} "></script>

	</body>
</html>